github: [alys5]
patreon: alys5creator
open_collective: alys5-portfolio
ko_fi: alys5
liberapay: alys5
issuehunt: alys5
polar: alys5
buy_me_a_coffee: alys5
thanks_dev: alys5
custom: ['https://fiverr.com/alys_5', 'https://alys5.eu/support']
